# ============== DJANGO ==============
DJANGO_PROJECT_PATH = 'Django/demo'
URLS_PATH = f'{DJANGO_PROJECT_PATH}/demo/urls.py'
VIEWS_PATH = f'{DJANGO_PROJECT_PATH}/demo/views.py'

# ============== FASTAPI ==============
FASTAPI_PROJECT_PATH = 'FastAPI/demo'
FA_MAIN_PATH = f'{FASTAPI_PROJECT_PATH}/main.py'

# ============== PYRAMID ==============
PYRAMID_PROJECT_PATH = 'Pyramid/demo'
PYRAMID_PACKAGE_NAME = 'pyrademo'
PYRAMID_PACKAGE_PATH = f'{PYRAMID_PROJECT_PATH}/{PYRAMID_PACKAGE_NAME}'
PYRAMID_INI_PATH = f'{PYRAMID_PROJECT_PATH}/development.ini'
PYRAMID_SETUP_PATH = f'{PYRAMID_PROJECT_PATH}/setup.py'
PYRAMID_INIT_PATH = f'{PYRAMID_PACKAGE_PATH}/__init__.py'
PYRAMID_VIEWS_PATH = f'{PYRAMID_PACKAGE_PATH}/views.py'
